image: gitlab.catalyst.net.nz:4567/silverstripe/security-development-lifecycle-tool/devenv/silverstripe4:16.04

before_script:
  - puppet-devenv-apply

test:
  tags: [kubernetes]
  only: [feature-gitlab-ci]
  script:
    - cd "${CI_PROJECT_DIR}"
    - composer --no-interaction install --prefer-dist
    - vendor/bin/phpunit
