image: gitlab.catalyst.net.nz:4567/silverstripe/security-development-lifecycle-tool/devenv/silverstripe4:18.04

before_script:
  - puppet-devenv-apply -t composer -d '{"devenv::tools::nodejs::version":"8.x"}'

test:
  tags:
    - kubernetes
  script:
    - cd "${CI_PROJECT_DIR}"
    - composer --no-interaction install --prefer-dist
    - vendor/bin/phpunit
