---
Name: nzta-sdlt-services
---

# Audit logging
NZTA\SDLT\Model\Questionnaire:
  dependencies:
    auditService: '%$NZTA\SDLT\Service\AuditService'
    
NZTA\SDLT\Model\QuestionnaireSubmission:
  dependencies:
    auditService: '%$NZTA\SDLT\Service\AuditService'
  
NZTA\SDLT\Model\Task:
  dependencies:
    auditService: '%$NZTA\SDLT\Service\AuditService'
  
NZTA\SDLT\Model\TaskSubmission:
  dependencies:
    auditService: '%$NZTA\SDLT\Service\AuditService'